/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package User_Interface;

import Business.VitalSigns;
import Business.VitalSignsHistory;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Urvi
 */
public class ViewJPanel extends javax.swing.JPanel {
    
    VitalSignsHistory history;

    /**
     * Creates new form ViewJPanel
     */
    public ViewJPanel(VitalSignsHistory history) {
        initComponents();
        this.history = history;
        displayTable();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lbltitleview = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblvitals = new javax.swing.JTable();
        btnviewtbl = new javax.swing.JButton();
        btndelete = new javax.swing.JButton();
        lbltitle = new javax.swing.JLabel();
        lbltemperature = new javax.swing.JLabel();
        lblpressure = new javax.swing.JLabel();
        lblpulse = new javax.swing.JLabel();
        lbldate = new javax.swing.JLabel();
        txttemperature = new javax.swing.JTextField();
        txtpressure = new javax.swing.JTextField();
        txtpulse = new javax.swing.JTextField();
        txtdate = new javax.swing.JTextField();

        lbltitleview.setText("View Vital Signs");

        tblvitals.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Date", "Temperature", "Blood Pressure"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(tblvitals);

        btnviewtbl.setText("View");
        btnviewtbl.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnviewtblActionPerformed(evt);
            }
        });

        btndelete.setText("Delete");
        btndelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btndeleteActionPerformed(evt);
            }
        });

        lbltitle.setText("Create Vital Signs");

        lbltemperature.setText("Temperature:");

        lblpressure.setText("Blood Pressure:");

        lblpulse.setText("Pulse:");

        lbldate.setText("Date:");

        txtpressure.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtpressureActionPerformed(evt);
            }
        });

        txtpulse.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtpulseActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(226, 226, 226)
                .addComponent(lbltitleview)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 502, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(136, 136, 136)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lblpressure)
                            .addComponent(lbltemperature)
                            .addComponent(lblpulse)
                            .addComponent(lbldate))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(txtpulse, javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(txtpressure)
                                .addComponent(txtdate, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(txttemperature, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnviewtbl)))
                .addGap(32, 32, 32)
                .addComponent(btndelete)
                .addGap(34, 34, 34))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(231, 231, 231)
                    .addComponent(lbltitle)
                    .addContainerGap(208, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lbltitleview)
                .addGap(30, 30, 30)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnviewtbl)
                    .addComponent(btndelete))
                .addGap(36, 36, 36)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbltemperature)
                    .addComponent(txttemperature, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblpressure)
                    .addComponent(txtpressure, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblpulse)
                    .addComponent(txtpulse, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbldate)
                    .addComponent(txtdate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(74, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(143, 143, 143)
                    .addComponent(lbltitle)
                    .addContainerGap(312, Short.MAX_VALUE)))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void txtpressureActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtpressureActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtpressureActionPerformed

    private void txtpulseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtpulseActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtpulseActionPerformed

    private void btndeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btndeleteActionPerformed
        int selectedRowIndex = tblvitals.getSelectedRow();
        if(selectedRowIndex < 0){
            JOptionPane.showMessageDialog(this, "Please select a row to delete");
        }
        
        DefaultTableModel model = (DefaultTableModel) tblvitals.getModel();
        VitalSigns selectedvitals = (VitalSigns) model.getValueAt(selectedRowIndex, 0);
        
        history.deleteVitals(selectedvitals);
        JOptionPane.showMessageDialog(this, "Selected Vitals have been deleted!");
        displayTable();
                
                
        // TODO add your handling code here:
    }//GEN-LAST:event_btndeleteActionPerformed

    private void btnviewtblActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnviewtblActionPerformed
        int selectedRowIndex = tblvitals.getSelectedRow();
        if(selectedRowIndex < 0){
            JOptionPane.showMessageDialog(this, "Please select a row to delete");
        }
        
        DefaultTableModel model = (DefaultTableModel) tblvitals.getModel();
        VitalSigns selectedvitals = (VitalSigns) model.getValueAt(selectedRowIndex, 0);
        
        txttemperature.setText(String.valueOf(selectedvitals.getTempertaure()));
        txtpressure.setText(String.valueOf(selectedvitals.getBloddPressure()));
        txtpulse.setText(String.valueOf(selectedvitals.getPulse()));
        txtdate.setText(String.valueOf(selectedvitals.getDate()));
        
        // TODO add your handling code here:
    }//GEN-LAST:event_btnviewtblActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btndelete;
    private javax.swing.JButton btnviewtbl;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lbldate;
    private javax.swing.JLabel lblpressure;
    private javax.swing.JLabel lblpulse;
    private javax.swing.JLabel lbltemperature;
    private javax.swing.JLabel lbltitle;
    private javax.swing.JLabel lbltitleview;
    private javax.swing.JTable tblvitals;
    private javax.swing.JTextField txtdate;
    private javax.swing.JTextField txtpressure;
    private javax.swing.JTextField txtpulse;
    private javax.swing.JTextField txttemperature;
    // End of variables declaration//GEN-END:variables

    private void displayTable() {
        DefaultTableModel model = (DefaultTableModel) tblvitals.getModel();
        model.setRowCount(0);
        
        for(VitalSigns vs : history.getHistory()){
            Object[] row = new Object[3];
            row[0] = vs;
            row[1] = vs.getTempertaure();
            row[2] = vs.getPulse();
            
            model.addRow(row);       
        }
    }
}